# Dependencies
markdown:         kramdown
highlighter:      rouge
baseurl: "/dmedia"

# Permalinks
permalink:        pretty

# Setup
title:            dachmedia.de
url:              http://www.dachmedia.de

repository:       dmedia/rendrap
